doc_manager_document_index:
    path:     /index
    defaults: { _controller: DocManagerDocumentBundle:Document:index }
doc_manager_document_edit:
    path:     /edit/{id}
    defaults: { _controller: DocManagerDocumentBundle:Document:edit}
doc_manager_document_add:
    path:     /add
    defaults: { _controller: DocManagerDocumentBundle:Document:add}
doc_manager_document_view:
    path:     /document/{id}
    defaults: { _controller: DocManagerDocumentBundle:Document:view}