doc_manager_document_index:
    path:     /index
    defaults: { _controller: DocManagerDocumentBundle:Document:index }
doc_manager_document_edit:
    path:     /edit/{slug}
    defaults: { _controller: DocManagerDocumentBundle:Document:edit}
doc_manager_document_add:
    path:     /add
    defaults: { _controller: DocManagerDocumentBundle:Document:add}
doc_manager_document_view:
    path:     /document/{slug}
    defaults: { _controller: DocManagerDocumentBundle:Document:view}
doc_manager_document_delete:
    path:     /delete/{slug}
    defaults: { _controller: DocManagerDocumentBundle:Document:delete }
doc_manager_document_out_of_date:
    path:     /out-of-date
    defaults: { _controller: DocManagerDocumentBundle:Document:outofdate }
doc_manager_document_search:
    path:     /search
    defaults: { _controller: DocManagerDocumentBundle:Document:search }