services:
#    doc_manager_document.example:
#        class: DocManager\DocumentBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    doc_manager_document.ckeditor:
        class: DocManager\DocumentBundle\Form\Type\CkeditorType
        tags:
            - { name: form.type, alias: ckeditor }
    doc_manger_document.datevalidator:
        class: DocManager\DocumentBundle\Validator\Constraints\DateConstraintValidator
        arguments:  [@security.context]
        tags:
            - { name: validator.constraint_validator, alias: date_validator}