<?php

namespace DocManager\DocumentBundle\Entity;

use DocManager\DocumentBundle\Entity\Category;
use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function getUnusedCategories()
    {
        $categorieUtilisee = array();
        $em = $this->_em;
        $documents = $em->getRepository('DocManagerDocumentBundle:Document')->findAll();
        foreach($documents as $document)
        {
            foreach($document->getCategories() as $categorie)
            {
                if(!in_array($categorie,$categorieUtilisee))
                {
                    array_push($categorieUtilisee, $categorie);
                }
            }
        }
        $query = $em->createQuery('SELECT c FROM DocManagerDocumentBundle:Category c WHERE c NOT IN (:unused)');
        $query->setParameter('unused',$categorieUtilisee);
        return $query->getResult();
    }
}
