<?php

namespace DocManager\DocumentBundle\Entity;

use DocManager\UserBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function getAllUserCategories(User $user)
    {
        $qb = $this->createQueryBuilder('d');

        // On fait une jointure avec l'entité Category avec pour alias « c »
        $qb
            ->join('d.categories', 'c')
            ->addSelect('c')
            ->join('d.user', 'u')
            ->addSelect('u')
        ;

        // Puis on filtre sur le nom des catégories à l'aide d'un IN
        $qb->where($qb->expr()->in('c.name', $categoryNames));
        $qb->where($qb->expr()->in('u.name', $categoryNames));
        // La syntaxe du IN et d'autres expressions se trouve dans la documentation Doctrine

        // Enfin, on retourne le résultat
        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
